name: wtf_sliding_sheet
description: A widget that can be dragged and scrolled in a single gesture and snapped to a list of extents.
version: 1.1.3
homepage: https://pub.dev/packages/wtf_sliding_sheet
repository: https://github.com/What-the-Flutter/wtf_sliding_sheet

topics:
  - bottomsheet
  - widget
  - dialog

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
